# Introdución a la libreria numpy

NumPy es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.

Para comenzar a usar numpy, se debe importar la librería. En este caso la vamos a importar, y darle un sobrenombre al mismo tiempo, **np**, para que el código sea más legible

In [1]:
# importamos la librería numpy, y le damos como nombre np dentro del programa
import numpy as np

Ahora que tenemos la librería, empecemos creando un vector de 5 elementos.

La manera más común de crear una un vector o matriz ya inicializada es con la función np.array, que toma una lista (o lista de listas) como parámetro y devuelve una matriz de numpy.

In [ ]:
import numpy as np
print

array([25. , 12. , 15. , 66. , 12.5])

In [ ]:
import random
print

<function print>

Un vector (a diferencia de una lista), al ser un arreglo de numpy, nos permite hacer varias operaciones matemáticas de forma muy simple.

In [ ]:
print("- sumarle 1 a cada elemento del vector:")
print(vector+1)
print("- multiplicar por 5 cada elemento del vector:")
print(vector*5)

- sumarle 1 a cada elemento del vector:
[26.  13.  16.  67.  13.5]
- multiplicar por 5 cada elemento del vector:
[125.   60.   75.  330.   62.5]


In [ ]:
print("- suma de los elementos:")
print(np.sum(vector))

- suma de los elementos:
130.5


In [ ]:
print("- promedio (media) de los elementos:")
print(np.mean(vector)) #

- promedio (media) de los elementos:
26.1


In [ ]:
print("- el vector sumado a si mismo:")
print(vector+vector)
print("- suma de vectores vector1 y vector2 (mismo tamaño):")
vector2=np.array([11,55,1.2,7.4,-8])
print(vector+vector2)

- el vector sumado a si mismo:
[ 50.  24.  30. 132.  25.]
- suma de vectores vector1 y vector2 (mismo tamaño):
[36.  67.  16.2 73.4  4.5]


## Índices y Slices de vectores
Así como con las listas, se utilizan los corchetes ([ ]) para acceder a sus elementos, y se pueden tomar slices o rebanadas del arreglo utilizando **:**

Nota: Los elementos de un vector empiezan en la posición 0

In [ ]:
print(vector[3]) # imprime el elemnto ubicado en la posición 3 del vector
print(vector[1:4]) # imprime los elementos desde la posición 1 hasta la 3
print(vector[1:]) # imprime todos los elementos desde la posición 1
print(vector[:4]) # imprime todos los elementos hasta la posición 3
print(vector[:]) # imprime todos los elementos similar a print(vector)

##Creación de vectores con valor 0 o 1
Es muy común crear un vector con valores 0 o 1. Por ejemplo, cuando se utiliza un vector de contadores, donde cada contador comienza en 0.

Para ello, se utiliza las funciones np.zeros y np.ones, respectivamente. Cada una toma como parámetro la cantidad de elementos del vector a crear.

In [ ]:
print("- Vector de ceros:")
vector_ceros=np.zeros(5)
print(vector_ceros)

print("- Vector de unos:")
vector_unos=np.ones(5)
print(vector_unos)


#Combinando este tipo de creaciones con las operaciones aritméticas,
#podemos hacer varias inicializaciones muy rápidamente
# Por ejemplo, para crear un vector cuyos valores iniciales son todos 2.

print("- Vector con todos los elementos con valor 2:")
vector_dos=np.zeros(5)+2
print(vector_dos)

print("- Vector con todos los elementos con valor 2 (otra forma):")
vector_dos_otro=np.ones(5)*2
print(vector_dos_otro)

- Vector de ceros:
[0. 0. 0. 0. 0.]
- Vector de unos:
[1. 1. 1. 1. 1.]
- Vector con todos los elementos con valor 2:
[2. 2. 2. 2. 2.]
- Vector con todos los elementos con valor 2 (otra forma):
[2. 2. 2. 2. 2.]


##Matrices
Los vectores son arreglos de una sola dimensión. Las matrices son arreglos de dos dimensiones; generalmente a la primera dimensión se la llama la de las filas, mientras que a la otra se la llama la de las columnas.

Por ende, para crearlas con np.array, necesitamos no una lista de valores, sino una lista de valores por cada fila, o sea, una lista de listas.

Del mismo modo, para crearlas con np.zeros o np.ones, vamos a necesitar una **tupla** con **dos** elementos, uno por cada dimensión.

In [ ]:
print("- Matriz creada con una lista de listas:")
lista_de_listas=[ [1  ,-4],
                  [12 , 3],
                  [7.2, 5]]
matriz = np.array(lista_de_listas)
print(matriz)


print("- Matriz creada con np.zeros:")
dimensiones=(2,3)
matriz_ceros = np.zeros(dimensiones)
print(matriz_ceros)


print("- Matriz creada con np.ones:")
dimensiones=(3,2)
matriz_unos = np.ones(dimensiones)
print(matriz_unos)

#también podemos usar np.copy para copiar una matriz
print("- Copia de la matriz creada con np.ones:")
matriz_unos_copia=np.copy(matriz_unos)
print(matriz_unos_copia)

- Matriz creada con una lista de listas:
[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]
- Matriz creada con np.zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
- Matriz creada con np.ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
- Copia de la matriz creada con np.ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


###Ejercicio
Crear una matriz de 4x9, que esté inicializada con el valor 0.5


In [ ]:
# Ingrese su código aquí


In [ ]:
print(matriz)

[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]]


###Accediendo a las matrices
También podemos usar slices para acceder a partes de las matrices. Las matrices tienen dos dimensiones, así que ahora tenemos que usar dos indices o slices para seleccionar partes.

In [ ]:
lista_de_listas=[ [1  ,-4],
                  [12 , 3],
                  [7.2, 5]]
a = np.array(lista_de_listas)

print("Elementos individuales")
print(a[0,1])
print(a[2,1])

print("Vector de elementos de la fila 1")
print(a[1,:])

print("Vector de elementos de la columna 0")
print(a[:,0])

print("Submatriz de 2x2 con las primeras dos filas")
print(a[0:2,:])

print("Submatriz de 2x2 con las ultimas dos filas")
print(a[1:3,:])

Elementos individuales
-4.0
5.0
Vector de elementos de la fila 1
[12.  3.]
Vector de elementos de la columna 0
[ 1.  12.   7.2]
Submatriz de 2x2 con las primeras dos filas
[[ 1. -4.]
 [12.  3.]]
Submatriz de 2x2 con las ultimas dos filas
[[12.   3. ]
 [ 7.2  5. ]]


###Modificando matrices
También podemos usar los slices para modificar matrices. La única diferencia es que ahora los usaremos para seleccionar que parte de la matriz vamos a cambiar.

In [ ]:
lista_de_listas=[ [1,-4],
                  [12,3],
                  [7, 5.0]]
a = np.array(lista_de_listas)

print("- Matriz original:")
print(a)

print("- Le asignamos el valor 4 a los elementos de la columna 0:")
a[:,0]=4
print(a)


print("- Dividimos por 3 la columna 1:")
a[:,1]=a[:,1]/3.0
print(a)

print("- Multiplicamos por 5 la fila 1:")
a[1,:]=a[1,:]*5
print(a)

print("- Le sumamos 1 a toda la matriz:")
a=a+1
print(a)

- Matriz original:
[[ 1. -4.]
 [12.  3.]
 [ 7.  5.]]
- Le asignamos el valor 4 a los elementos de la columna 0:
[[ 4. -4.]
 [ 4.  3.]
 [ 4.  5.]]
- Dividimos por 3 la columna 1:
[[ 4.         -1.33333333]
 [ 4.          1.        ]
 [ 4.          1.66666667]]
- Multiplicamos por 5 la fila 1:
[[ 4.         -1.33333333]
 [20.          5.        ]
 [ 4.          1.66666667]]
- Le sumamos 1 a toda la matriz:
[[ 5.         -0.33333333]
 [21.          6.        ]
 [ 5.          2.66666667]]


##Ejercicios

Tomando la siguiente matriz

In [ ]:
lista_de_listas=[ [-44,12],
                  [12.0,51],
                  [1300, -5.0]]
a = np.array(lista_de_listas)

* Restarle 5 a la fila 2 de la matriz

* Multiplicar por 2 toda la matriz

* Dividir por -5 las dos primeras filas de la matriz

In [ ]:
random.randint(1,6)

2

In [ ]:
random.randint(1,6)

3

In [ ]:
random.random()

0.3943939003974677

In [ ]:
dir(random)

['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_BuiltinMethodType',
 '_MethodType',
 '_Sequence',
 '_Set',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_inst',
 '_itertools',
 '_log',
 '_pi',
 '_random',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 '_warn',
 'betavariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

In [ ]:
import random

In [ ]:
jugando = true
while jugando:
  print("Juego de, "piedra", "papel", "tijera".")
  ordenador = random.choice(["piedra", "papel", "tijera"])
  jugador = input("Elige una opcion: ")
  if jugador == "piedra":
    if ordenador == "piedra":
      print("ordenador elige "piedra". Empate.")
      elif ordenador == "papel":
        print("ordenador elige "papel". Papel envuelve piedra. Pierdes.")
        Else:
        print("ordenador elige "tijera". Piedra rompe tijera. Ganas.")
        elif jugador == "papel":
          if ordenador == "piedra":
            print("ordenador elige "piedra". Papel envuelve piedra. Ganas.")
            elif ordenador == "papel":
              print("ordenador elige "papel". Empate.")
              else:
                print("ordenador elige "tijeras". Tijeras corta papel. Pierdes.")
                elif jugador == "tijeras":
                  if ordenador == "piedra":
                    print("ordenador elige "piedra". Piedra rompe tijeras. Pierdes.")
                    elif ordenador == "papel":
                      print("ordenador elige "papel". Tijera cortan papel. Ganas")






* Imprimir la ultima fila de la matriz

## Referencias
* https://numpy.org/devdocs/user/quickstart.html
* http://facundoq.github.io/courses/images/res/03_numpy.html